version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=pg
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
  web:
    build: .
    command: bash -c "sleep 10 && python manage.py makemigrations && python manage.py migrate && python fire.py"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
