version: '3'

services:
  redis:
      image: redis
      container_name: 'app_redis'
      command: redis-server
      ports:
        - '6379:6379'
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=pg
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  celery:
      build: .
      command: celery -A core worker -B
      volumes:
        - .:/code
      links:
        - redis
      depends_on:
        - web
        - redis